openapi: 3.0.3
info:
  title: Project API
  description: API quản lý thông tin dự án và vé (ticket) liên quan.
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api'
    description: Server chính của API
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Project:
      type: object
      properties:
        id:
          type: integer
          description: ID duy nhất của dự án
          example: 101
        name:
          type: string
          description: Tên dự án
          example: Miss Joanna Leuschke
        startDate:
          type: string
          format: date
          description: Ngày bắt đầu dự án
          example: 2025-04-04
        endDate:
          type: string
          format: date
          description: Ngày kết thúc dự án
          example: 2025-05-05
        projectType:
          type: string
          enum: [FIX_PRICE, MAINTENANCE,LABOUR]
          description: Loại dự án
          example: MAINTENANCE
        profit:
          type: number
          nullable: true
          description: Lợi nhuận của dự án
          example: null
      required:
        - id
        - name
        - startDate
        - endDate
        - projectType
    Ticket:
      type: object
      properties:
        ticketId:
          type: integer
          description: ID của vé
          example: 234
        deadline:
          type: string
          format: date
          description: Ngày hết hạn của vé
          example: 2025-03-25
      required:
        - ticketId
    TicketCountReport:
      type: object
      properties:
        projectId:
          type: integer
          description: ID của dự án
          example: 48
        projectName:
          type: string
          description: Tên dự án
          example: Chester Johnson IV
        ticketCount:
          type: integer
          description: Số lượng vé của dự án
          example: 34
      required:
        - projectId
        - projectName
        - ticketCount
    PaginatedTicketCountResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/TicketCountReport'
          description: Danh sách các dự án với số lượng vé
        meta:
          type: object
          properties:
            total:
              type: integer
              description: Tổng số dự án
              example: 5185
            currentPage:
              type: integer
              description: Trang hiện tại
              example: 3
            limit:
              type: integer
              description: Số lượng bản ghi trên mỗi trang
              example: 3
            totalPages:
              type: integer
              description: Tổng số trang
              example: 1729
          required:
            - total
            - currentPage
            - limit
            - totalPages
      required:
        - data
        - meta
    Error:
      type: object
      properties:
        message:
          type: string
          description: Thông báo lỗi
          example: Không tìm thấy dự án
      required:
        - message
paths:
  /projects/{projectId}:
    get:
      summary: Lấy thông tin dự án
      description: Lấy chi tiết thông tin của một dự án dựa trên ID.
      operationId: getProjectById
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
          description: ID của dự án cần lấy thông tin
      responses:
        '200':
          description: Thành công, trả về thông tin dự án
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          description: Không tìm thấy dự án
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: Cập nhật thông tin dự án
      description: Cập nhật thông tin của một dự án dựa trên ID.
      operationId: updateProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
          description: ID của dự án cần cập nhật
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Tên mới của dự án
                  example: Miss Joanna1
                startDate:
                  type: string
                  format: date-time
                  description: Ngày bắt đầu mới
                  example: 2024-04-19T18:58:59.000Z
                endDate:
                  type: string
                  format: date-time
                  description: Ngày kết thúc mới
                  example: 2024-04-25T18:58:59.000Z
                projectType:
                  type: string
                  enum: [FIX_PRICE, MAINTENANCE,LABOUR]
                  description: Loại dự án mới
                  example: MAINTENANCE
                profit:
                  type: number
                  nullable: true
                  description: Lợi nhuận mới của dự án
                  example: null
              required:
                - name
                - startDate
                - endDate
                - projectType
      responses:
        '200':
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Không tìm thấy dự án
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Xóa dự án
      description: Xóa một dự án dựa trên ID.
      operationId: deleteProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
          description: ID của dự án cần xóa
      responses:
        '204':
          description: Xóa dự án thành công
        '404':
          description: Không tìm thấy dự án
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /projects:
    get:
      summary: Lấy danh sách dự án
      description: Lấy danh sách các dự án với tùy chọn lọc và phân trang.
      operationId: getProjects
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
          description: Tên dự án để tìm kiếm
          example: Edgar Ledner
        - name: projectType
          in: query
          required: false
          schema:
            type: string
            enum: [FIX_PRICE, MAINTENANCE,LABOUR]
          description: Loại dự án để lọc
          example: FIX_PRICE
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Số lượng bản ghi trên mỗi trang
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: Số trang hiện tại
      responses:
        '200':
          description: Thành công, trả về danh sách dự án
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
        '400':
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Tạo dự án mới
      description: Tạo một dự án mới với thông tin được cung cấp.
      operationId: createProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Tên dự án
                  example: Miss Joanna Leuschke2
                startDate:
                  type: string
                  format: date
                  description: Ngày bắt đầu dự án
                  example: 2025-04-04
                endDate:
                  type: string
                  format: date
                  description: Ngày kết thúc dự án
                  example: 2025-05-05
                projectType:
                  type: string
                  enum: [FIX_PRICE, MAINTENANCE,LABOUR]
                  description: Loại dự án
                  example: MAINTENANCE
                profit:
                  type: number
                  nullable: true
                  description: Lợi nhuận của dự án
                  example: null
              required:
                - name
                - startDate
                - endDate
                - projectType
      responses:
        '201':
          description: Tạo dự án thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /projects/{projectId}/tickets:
    get:
      summary: Lấy danh sách vé của dự án
      description: Lấy danh sách các vé (ticket) thuộc một dự án cụ thể, với tùy chọn lọc theo khoảng thời gian.
      operationId: getProjectTickets
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
          description: ID của dự án
        - name: from
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Ngày bắt đầu của khoảng thời gian
          example: 2025-01-01
        - name: to
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Ngày kết thúc của khoảng thời gian
          example: 2025-10-10
      responses:
        '200':
          description: Thành công, trả về danh sách vé
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'
        '400':
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Không tìm thấy dự án hoặc vé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /projects/filter:
    get:
      summary: Lọc dự án theo doanh thu hoặc ngày bắt đầu
      description: Lấy danh sách dự án dựa trên tiêu chí lọc về ngày bắt đầu hoặc lợi nhuận.
      operationId: filterProjects
      parameters:
        - name: startDate
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Ngày bắt đầu để lọc dự án
          example: 2025-01-06
        - name: profit
          in: query
          required: false
          schema:
            type: number
          description: Lợi nhuận tối thiểu để lọc dự án
          example: 40000
      responses:
        '200':
          description: Thành công, trả về danh sách dự án
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
        '400':
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /projects/reports/ticket-count:
    get:
      summary: Lấy số lượng vé theo dự án
      description: Lấy số lượng vé được gán cho từng dự án với phân trang.
      operationId: getTicketCountByProject
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Số lượng bản ghi trên mỗi trang
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: Số trang hiện tại
      responses:
        '200':
          description: Thành công, trả về danh sách số lượng vé theo dự án
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTicketCountResponse'
        '400':
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'