openapi: 3.0.3
info:
  title: User API
  description: API quản lý thông tin người dùng và vé (ticket) liên quan.
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api'
    description: Server chính của API
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: ID duy nhất của người dùng
          example: 101
        name:
          type: string
          description: Tên người dùng
          example: Javon
        username:
          type: string
          description: Tên đăng nhập của người dùng
          example: Esther92
        email:
          type: string
          format: email
          description: Địa chỉ email của người dùng
          example: esther92@example.com
        avatar:
          type: string
          nullable: true
          description: URL hoặc đường dẫn tới ảnh đại diện của người dùng
          example: null
      required:
        - id
        - name
        - username
        - email
    Error:
      type: object
      properties:
        message:
          type: string
          description: Thông báo lỗi
          example: Không tìm thấy người dùng
      required:
        - message
paths:
  /users/{userId}:
    get:
      summary: Lấy thông tin người dùng
      description: Lấy chi tiết thông tin của một người dùng dựa trên ID.
      operationId: getUserById
      security:
        - BearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID của người dùng cần lấy thông tin
      responses:
        '200':
          description: Thành công, trả về thông tin người dùng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Không tìm thấy người dùng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: Cập nhật thông tin người dùng
      description: Cập nhật thông tin của một người dùng dựa trên ID.
      operationId: updateUser
      security:
        - BearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID của người dùng cần cập nhật
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Tên mới của người dùng
                  example: Javon
                username:
                  type: string
                  description: Tên đăng nhập mới
                  example: Esther92
                password:
                  type: string
                  description: Mật khẩu mới
                  example: RvJQjTZecw8eXzV23
              required:
                - name
                - username
                - password
      responses:
        '200':
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Không tìm thấy người dùng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users:
    get:
      summary: Lấy danh sách người dùng theo tên đăng nhập
      description: Lấy danh sách người dùng dựa trên tên đăng nhập với phân trang.
      operationId: getUsersByUsername
      security:
        - BearerAuth: []
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
          description: Tên đăng nhập để tìm kiếm
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Số lượng bản ghi trên mỗi trang
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: Số trang hiện tại
      responses:
        '200':
          description: Thành công, trả về danh sách người dùng
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Tạo người dùng mới
      description: Tạo một người dùng mới với thông tin được cung cấp.
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Tên người dùng
                  example: Javon3
                username:
                  type: string
                  description: Tên đăng nhập
                  example: Esther922
                password:
                  type: string
                  description: Mật khẩu
                  example: RvJQjTZecw8eXzV
                avatar:
                  type: string
                  nullable: true
                  description: URL hoặc đường dẫn tới ảnh đại diện
                  example: null
              required:
                - name
                - username
                - password
      responses:
        '201':
          description: Tạo người dùng thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/{userId}/tickets:
    get:
      summary: Lấy danh sách vé của người dùng
      description: Lấy danh sách các vé (ticket) được gán cho một người dùng cụ thể.
      operationId: getUserTickets
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID của người dùng
      responses:
        '200':
          description: Thành công, trả về danh sách vé
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ticketId:
                      type: integer
                      description: ID của vé
                      example: 234
        '404':
          description: Không tìm thấy người dùng hoặc vé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Phân công vé cho người dùng
      description: Gán một hoặc nhiều vé cho một người dùng cụ thể.
      operationId: assignTickets
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID của người dùng cần gán vé
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ticketId:
                  type: array
                  items:
                    type: integer
                  description: Danh sách ID của các vé cần gán
                  example: [234]
              required:
                - ticketId
      responses:
        '200':
          description: Gán vé thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Thông báo xác nhận
                    example: Gán vé thành công
        '400':
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Không tìm thấy người dùng hoặc vé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'